-- T0010_010 EDA08 HSS VOLTE GPRSAM 5GSA

Insert into PROV_Q (SRV_TRX_S_NO,SYS_CREATION_DATE,SYS_UPDATE_DATE,OPERATOR_ID,APPLICATION_ID,DL_SERVICE_CODE,DL_UPDATE_STAMP,PRIM_RESOURCE_VAL,PRIM_RES_PARAM_CD,MARKET_CODE,PRIORITY,IGN_SUB_DEPEND_IND) values (10010,sysdate,null,41004,null,'CS030',null,'11989292319','MSISDN','MTA',null,'N');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'CUSTOMER=860745524;SUBSCRIBER_STATUS=A;PRICE_PLAN=380523526;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=HSS;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=GPRSAM;FTR_STATUS=A;EQOSID=314;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=5GSA;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=MSISDN;FTR_STATUS=A;MSISDN=11989292319;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=SIMCARD;FTR_STATUS=A;ICCID=89550500018000000032;IMSI=724050823647677;PIN_1=3636;PUK_1=67119043;TRANSK=26;KI=qhMKhlNNNBI5ssNLeeGKhsM4NMOBHllHOO;PIN_2=1138;CHV5=1F8EB45B9E594087;PUK_2=29488192;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=!TWC;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=VIDEO;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=DNLD;FTR_STATUS=A;EQOSID=308;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=MMS;FTR_STATUS=A;EQOSID=305;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=VSTRM;FTR_STATUS=A;EQOSID=308;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=WAP;FTR_STATUS=A;EQOSID=304;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=BOCL21;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=B900;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CLIP;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=TWC;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CFU;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CAW;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CSD;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=SMO;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=SMS;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=VMREC;FTR_STATUS=A;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=SOCCTR;FTR_STATUS=A;SOCCTR=380811888;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=RTCI11;FTR_STATUS=A;FLGPRG=0;FLGRC=1;CODPCT=201503272101;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=SUBTP;FTR_STATUS=A;SUBSCRIBER_TYPE=PG3G;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=VPNST;FTR_STATUS=A;CC=154945754;CCNM=DENISE MANTOVANI CINESI;DPTO1=154945754;DPTONM1=DENISE MANTOVANI CINESI;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=PRODT;FTR_STATUS=A;PRODUCT_TYPE=AR;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=RSNCD;FTR_STATUS=A;REASON_CODE=WNP;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CUSTT;FTR_STATUS=A;CUSTOMER_TYPE=I;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=SUBNO;FTR_STATUS=A;SUBSCRIBER_NO=320161784;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=PYMCA;FTR_STATUS=A;PAYMENT_CATEGORY= ;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=MKTCD;FTR_STATUS=A;MARKET_CODE=MTA;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=PRTY;FTR_STATUS=A;PRIORITY=0;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CLIID;FTR_STATUS=A;CLIENT_ID= ;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=SRVTR;FTR_STATUS=A;SRV_TRX_TP_CD=CANSUB;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=FRTXT;FTR_STATUS=A;FREE_TEXT= ;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CMPCD;FTR_STATUS=A;COMPANY_CODE=AC;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CNPJ;FTR_STATUS=A;CNPJ_VAL= ;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CPF;FTR_STATUS=A;CPF_VAL=04951449838;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=CUSTN;FTR_STATUS=A;CUSTNM=DENISE MANTOVANI CINESI;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=BLCYC;FTR_STATUS=A;BILLCYC=88;BLDAY=18;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=WNP;FTR_STATUS=A;WNP_ID=;');
Insert into PROV_Q_FTR(SRV_TRX_S_NO, NEW_OR_PREV, FEATURES) Values (10010, 'N', 'FTRCD=SUBNM;FTR_STATUS=A;SUBSCRIBER_NAME=DENISE MANTOVANI CINESI;');

commit;

--
set define off;
execute pkg_interface.move_records('POS')
--